jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: dv-img
     - TASK: managed

  - name: dv-img
    type: deploy
    steps:
      - IN: pipelines-demo-manifest
      - IN: dv-img-opts
      - IN: env-test-ecs
      - TASK: managed
        deployMethod: upgrade
