jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image-prem
     - TASK: managed

  - name: deploy-pipelines-demo
    type: deploy
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster-prem
      - TASK: managed
        deployMethod: upgrade
